export const formContainer: string;
export const formDetails: string;
export const formFooter: string;
export const formPanel: string;
export const formSubmit: string;
export const header: string;
export const inputGroup: string;
export const inputHeader: string;
export const row: string;
